# User Coherence Evaluation on Foundry Agent Traces

Evaluates user coherence (derail detection) on multi-turn conversations fetched from Azure AI Foundry agents:
- **legal-contract-review-sim** (20 conversations)
- **airline-customer-service-sim** (30 conversations)

Each conversation is evaluated independently, producing per-step derail scores and an aggregate mean score.

In [ ]:
import json
import os
import asyncio
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# All files (datasets, .env, results) live in the same directory as this notebook
load_dotenv()

# Import evaluator and trace normalizer
from azure.ai.evaluation._evaluators._user_coherence._user_coherence import (
    UserCoherenceEvaluator,
    normalize_trace_messages,
)

# Load datasets (produced by fetch_agent_conversations.py in the same folder)
AGENTS = os.environ.get("AGENTS", "legal-contract-review-sim,airline-customer-service-sim").split(",")

datasets = {}
for agent_name in AGENTS:
    filename = f"{agent_name}_conversations.json"
    if not Path(filename).exists():
        print(f"WARNING: {filename} not found — run fetch_agent_conversations.py first")
        continue
    with open(filename, encoding="utf-8") as f:
        datasets[agent_name] = json.load(f)
    print(f"Loaded {len(datasets[agent_name])} conversations for {agent_name}")

Loaded 20 conversations for legal-contract-review-sim
Loaded 30 conversations for airline-customer-service-sim

## Preview: Normalize Trace Messages

The raw trace messages from Foundry use `output_text`/`input_text` content types and include extra metadata. `normalize_trace_messages()` converts them to simple `{"role": ..., "content": ...}` dicts.

In [7]:
# Preview normalization on the first conversation of each agent
# NOTE: Foundry conversations.items.list() returns messages in reverse chronological order (newest first),
# so we reverse them to get the correct conversation flow.
for agent_name, convs in datasets.items():
    raw_msgs = convs[0]["messages"]
    # Reverse to chronological order, then normalize
    normalized = normalize_trace_messages(list(reversed(raw_msgs)))
    print(f"\n=== {agent_name} (conversation {convs[0]['conversation_id']}) ===")
    print(f"Raw messages: {len(raw_msgs)}, Normalized: {len(normalized)}")
    for msg in normalized:
        print(f"  [{msg['role']}] {msg['content']}...")

=== legal-contract-review-sim (conversation conv_f77aa9489231d2c000qnNW5b8ksh2XPCbH7JIWhjL6uMr4XGVE) ===
Raw messages: 10, Normalized: 10
  [user] Hey, this is Omar Salim. Quick one — is the limitation of liability clause in this SaaS contract safe to sign? I need to get it back today....
  [assistant] Thanks, Omar. To give you a proper recommendation, I'll need to:

1. Check the contract metadata (so I know the jurisdiction and relevant policies).
2. Find and read the actual limitation of liability clause.

I’ll get started now.

[TOOL CALL] get_contract_metadata({"contract_id": "saas-2024-omar"})

[TOOL RESULT] {
  "parties": ["Salim Enterprises LLC", "CloudLogic Inc."],
  "effective_date": "2024-06-10",
  "governing_law": "New York",
  "jurisdiction": "New York",
  "contract_type": "SaaS Master Agreement",
  "page_count": 22
}

[TOOL CALL] list_clauses({"contract_id": "saas-2024-omar"})

[TOOL RESULT] {
  "clauses": [
    {"clause_id": "1.1", "heading": "Definitions", "page": 1},
    {"clause_id": "2.1", "heading": "Services Provided", "page": 3},
    {"clause_id": "7.3", "heading": "Limitation of Liability", "page": 14},
    {"clause_id": "8.1", "heading": "Indemnification", "page": 15},
    {"clause_id": "9.4", "heading": "Term and Termination", "page": 17},
    {"clause_id": "10.2", "heading": "Intellectual Property", "page": 19},
    {"clause_id": "11.5", "heading": "Confidentiality", "page": 20},
    {"clause_id": "12.7", "heading": "Governing Law; Jurisdiction", "page": 21}
  ]
}

[TOOL CALL] get_clause({"contract_id": "saas-2024-omar", "clause_id": "7.3"})

[TOOL RESULT] {
  "clause_id": "7.3",
  "heading": "Limitation of Liability",
  "text": "EXCEPT FOR LIABILITY ARISING FROM BREACH OF CONFIDENTIALITY, INDEMNIFICATION, OR CUSTOMER’S OBLIGATION TO PAY FEES UNDER THIS AGREEMENT, NEITHER PARTY SHALL BE LIABLE TO THE OTHER FOR ANY INDIRECT, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE AGGREGATE LIABILITY OF EITHER PARTY UNDER THIS AGREEMENT SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY CUSTOMER TO CLOUDLOGIC INC. IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO SUCH LIABILITY. NOTHING IN THIS SECTION SHALL LIMIT LIABILITY FOR GROSS NEGLIGENCE OR WILLFUL MISCONDUCT.",
  "cross_references": ["Section 11.5", "Section 8.1"]
}

To give a complete answer, let me check your company’s policy on liability caps and see what’s “market standard” in New York. I’ll also scan for relevant jurisdiction rules.

[TOOL CALL] get_company_policy({"topic": "limitation_of_liability"})

[TOOL RESULT] {
  "policy": "Liability must be capped at a 12-month fee amount for all claims except for uncapped indemnity, confidentiality, and payment obligations. Indirect damages must be excluded. Cap cannot be excluded for breaches of confidentiality or indemnity."
}

[TOOL CALL] lookup_precedent({"clause_type": "limitation_of_liability", "jurisdiction": "New York"})

[TOOL RESULT] {
  "precedent": "Standard liability cap is 12 months fees, with carve-outs for confidentiality, indemnity, payment obligations. Indirect damages exclusion is typical. Caps for confidentiality and indemnity sometimes negotiated but typically uncapped for both."
}

Summary of clause 7.3:
- Indirect damages (like lost profits) are excluded, except where liability arises from breach of confidentiality, indemnity, or payment.
- For other claims, the cap is 12 months of fees.
- No cap or exclusion for gross negligence or willful misconduct.
- Cross-references to indemnification and confidentiality.

**Is it safe to sign?**
This clause is in line with your company policy and New York market standard. Indemnity, confidentiality, and payment obligations are uncapped, which is typical but means those exposures are unlimited—worth reviewing the actual indemnity (Section 8.1) and confidentiality (Section 11.5) clauses if you want to be extra thorough.

**Practical Impact:**
- Most claims are capped at 12 months SaaS fee payments.
- If you breach confidentiality or get hit with indemnity, liability is uncapped.
- Indirect damages excluded, protecting against excessive claims.
- Clause does not limit liability for gross negligence or willful misconduct (good for fairness and compliance).

**Short answer:**
The limitation of liability clause is safe to sign based on your policy and market precedent in New York. If you want to double-check the indemnity or confidentiality scope (where liability is uncapped), let me know—otherwise, you should be clear to proceed....
  [user] Thanks, but can you check the indemnity clause too? Just want to make sure there’s nothing sneaky in there before I sign....
  [assistant] Absolutely, Omar. I’ll pull and review the actual indemnity clause (Section 8.1), quote any key text, and check if its scope exposes you to unusual or excessive risks—especially since liability for indemnity is uncapped.

[TOOL CALL] get_clause({"contract_id": "saas-2024-omar", "clause_id": "8.1"})

[TOOL RESULT] {
  "clause_id": "8.1",
  "heading": "Indemnification",
  "text": "CloudLogic Inc. shall indemnify, defend, and hold harmless Customer from and against any and all claims, damages, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising out of or relating to (a) any alleged infringement of third-party intellectual property rights by CloudLogic Inc.’s services; (b) CloudLogic Inc.’s gross negligence or willful misconduct; (c) breach of this Agreement by CloudLogic Inc. Customer shall indemnify, defend, and hold harmless CloudLogic Inc. from and against any and all claims, damages, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising out of or relating to (i) Customer’s use of the services in violation of applicable law; (ii) Customer’s gross negligence or willful misconduct; (iii) breach of this Agreement by Customer.",
  "cross_references": []
}

**Indemnity Clause Analysis (8.1):**

- **CloudLogic Inc. indemnifies you (Salim Enterprises LLC) for:**
  - IP infringement by their services
  - Their gross negligence or willful misconduct
  - Their breach of contract

- **You indemnify CloudLogic Inc. for:**
  - Your use of the services in violation of law
  - Your gross negligence or willful misconduct
  - Your breach of contract

This is a reciprocal (balanced) indemnity clause—each party is responsible for its own misconduct, breach, and (for CloudLogic) IP infringement. No “sneaky” burdens are placed on you (e.g., indemnifying for partner misconduct, third-party claims unrelated to your use, or for CloudLogic's own actions).

**Risks:**
- Indemnity liability is uncapped (from the limitation clause), so if you breach—especially violating laws with use, gross negligence, or breach—you could be liable for unlimited damages.
- The scope is typical; indemnities aren’t triggered by “errors or omissions” or ambiguous actions. Only actual breach, illegal use, or gross negligence.

**Market Comparison:**
- Cross-checking New York precedent, this structure (mirror indemnity for IP, contract breach, gross negligence) is standard.

**Recommendation:**
There’s nothing unusual or “sneaky” in this indemnity clause. It’s balanced and aligns with your company policy and market practice.
Just make sure your team uses the SaaS in compliance with law and contract terms (to avoid uncapped exposure).

If you have specific concerns (e.g., do you use the SaaS in a regulated industry where risk is higher?), let me know—but otherwise, this indemnity clause is safe to sign....
  [user] Okay, thanks for checking that. Just to be clear, there’s no hidden way I could get stuck with a giant uncapped bill if, say, there’s a data breach or some security issue? That’s my main worry....
  [assistant] Great question, Omar. Let’s walk through whether you could face uncapped liability for a data breach or security issue, based on the actual contract text:

**Relevant Clauses:**
- **Limitation of Liability (7.3):** Liability is uncapped for indemnity, confidentiality breaches, and payment obligations.
- **Indemnification (8.1):** You indemnify CloudLogic Inc. only for:
  - Your use in violation of law,
  - Your gross negligence or willful misconduct,
  - Your breach of the Agreement.

You are **not** required to indemnify CloudLogic Inc. for any third-party claims arising solely out of a data breach or security issue unless:
- The breach was caused by your gross negligence/willful misconduct, OR
- It arose from your breach of contract, OR
- You used the service unlawfully.

**Uncapped Liability Applies If:**
- **You are at fault** in one of the ways above: uncapped liability would apply.
- If **CloudLogic Inc. is at fault** (e.g., their service is breached due to their own negligence or breach): they indemnify you, per clause 8.1.

**Confidentiality (Section 11.5):** Cross-referenced in the liability clause; typically, breaches (including data breaches) can be uncapped. Let me check the confidentiality clause’s actual language for complete clarity.

[TOOL CALL] get_clause({"contract_id": "saas-2024-omar", "clause_id": "11.5"})

[TOOL RESULT] {
  "clause_id": "11.5",
  "heading": "Confidentiality",
  "text": "Each party agrees to treat all non-public information received from the other party as confidential and shall use reasonable measures to protect against unauthorized disclosure. Confidential information shall not include information that (i) is or becomes publicly available other than through breach of this Agreement, (ii) is independently developed without reference to confidential information, or (iii) is lawfully received from a third party without restriction. Breach of this section will entitle the non-breaching party to seek all available legal and equitable remedies."
}

**Key Takeaways:**
- If the data breach involves your disclosure of CloudLogic’s confidential information (due to your own gross negligence, breach, or unlawful use), and they suffer damages, you could face uncapped liability.
- If CloudLogic Inc. suffers a security breach (e.g., their SaaS is compromised), *they* are responsible unless you contributed by breaching contract, acting unlawfully, or with gross negligence.

**No Hidden Traps:**
- You are **not** liable for all possible data breaches—only if it’s a breach caused by your conduct (as above).
- If you are careful with your use and do not violate the agreement or act with gross negligence, your liability is capped.
- There are no hidden provisions extending uncapped liability to routine data breaches or issues outside your control.

**Bottom Line:**
You will not get stuck with a giant uncapped bill for a data breach or security issue unless:
- The breach is a result of your gross negligence, willful misconduct, breach of Agreement, or unlawful use.
- Otherwise, your liability is capped at 12 months’ fees, except for confidentiality and indemnity, which are uncapped but apply as described above.

**Recommendation:**
If you’re reasonably careful and don’t violate the contract or act recklessly, you’re well-protected. If your business has unusual exposure (e.g., you deal with highly sensitive personal data), consider extra insurance or add further contractual safeguards—but for most SaaS uses, you should be safe to sign.

Let me know if you want to see sample language to further protect yourself or have other concerns. Otherwise, you’re clear to proceed....
  [user] Thanks, that helps. Just to double confirm—so the only way I’d face unlimited liability is if I mess up confidentiality or break the law or contract, but not for a regular hack or outage on their end? I just want to be sure there’s nothing buried that could catch me out....
  [assistant] You’re exactly right, Omar—and let me give you a clear confirmation based on the contract text:

### **Unlimited Liability Applies ONLY IF:**
- **You breach confidentiality** (e.g., you improperly disclose CloudLogic’s confidential information).
- **You breach the contract** (e.g., violate SaaS terms in a way that causes damages).
- **You use the SaaS unlawfully** (e.g., use the service for illegal activities).
- **You act with gross negligence or willful misconduct** (e.g., intentionally or negligently create massive risk).

These are the only triggers for uncapped liability on your side. This is spelled out in:
- **Limitation of Liability (7.3):** Caps liability except for indemnity, confidentiality, or payment obligations.
- **Indemnification (8.1):** You indemnify only for your breach, gross negligence, or unlawful use—not for third-party hacks or routine outages.
- **Confidentiality (11.5):** Requires reasonable protection of information; uncapped liability is triggered only if you breach this obligation.

### **What Isn’t Uncapped:**
- **Regular hacks, outages, or breaches on their end:** You are **not** liable unless you caused the issue through contract breach, unlawful use, or gross negligence.
- **Events outside your control:** No uncapped exposure for incidents not directly attributable to your misconduct.

### **Hidden Traps?**
- Based on the actual contract language, there aren’t hidden terms that sneak in uncapped liability for normal SaaS risks. The triggers for unlimited liability are clear and conventional.

### **Bottom Line for You:**
- As long as you operate responsibly—don’t intentionally violate confidentiality, applicable law, or the contract—the limitation of liability protects you.
- If CloudLogic is hacked or suffers an outage (and you didn’t cause it), you are not exposed to uncapped claims.
- If you do cause a breach (through negligence or misconduct), uncapped liability could apply—but that’s standard and expected.

**Your summary:**
You won’t get stuck with unlimited liability for routine SaaS issues caused by the vendor. Only your own breach of contract, confidentiality, or law, or gross negligence triggers uncapped exposure. Nothing unusual or buried in this contract.

If you want to reduce risk further (e.g., absolutely cap confidentiality/indemnity), I can propose specific language—but as written, this is already industry-standard and safe for you to sign.

Let me know if you need anything else or want to see a specific redline before you send it back!...
  [user] That’s super clear, thanks for walking through it. No need for a redline if this matches market and our policy—I’ll go ahead and sign. Appreciate the quick help!...
  [assistant] Glad I could help, Omar! You’re making a well-informed decision—the contract’s liability and indemnity structure directly matches both your company policy and New York market practice. No hidden risks for uncapped liability outside clear, conventional triggers.

If you ever need a deep dive on termination, renewal, or data handling in a contract, or want a specific redline, I’m here. Good luck with launching your SaaS—and let me know if any new contracts come up!

If you’re all set, just close the review with [END]....

=== airline-customer-service-sim (conversation conv_90b677c1b52c2aaa002Jy9lpFhI25DS0yl6YHs3zsPciBw1uSu) ===
Raw messages: 8, Normalized: 8
  [user] Hi, I need to change my flight to an earlier one on the same day. My booking reference is YK4J2M. Can you help me see what options are available?...
  [assistant] Absolutely, I can assist with that. To take a look at alternate flights and change options, may I have your last name as it appears on your booking? I'll also need to confirm the route and travel date so I can find suitable earlier flights for you....
  [user] Sure, the last name on the booking is Patel. The flight is from Chicago to Seattle on June 17th. Can you tell me what earlier options there are?...
  [assistant] Thank you for providing those details. Before I can present alternate flights, I’ll first check your reservation details for eligibility and then search for earlier flights from Chicago to Seattle on June 17th.

[TOOL CALL] lookup_reservation({"pnr":"YK4J2M"})

[TOOL RESULT] {
  "pnr": "YK4J2M",
  "passengers": [
    {"passenger_id": "P1", "first_name": "Amit", "last_name": "Patel", "date_of_birth": "1986-03-22"}
  ],
  "flights": [
    {
      "flight_number": "AS213",
      "date": "2024-06-17",
      "origin": "ORD",
      "destination": "SEA",
      "scheduled_departure": "17:45",
      "fare_class": "Economy"
    }
  ],
  "ticket_status": "ACTIVE",
  "baggage_info": [
    {"checked_bags": 1}
  ]
}

[TOOL CALL] get_fare_rules({"pnr": "YK4J2M"})

[TOOL RESULT] {
  "refundable": false,
  "changeable": true,
  "change_fee": 75,
  "cancel_policy": "Travel credit only",
  "fare_class_restrictions": "May change flights with $75 fee; difference in fare applies. Refund as travel credit only if cancelled."
}

[TOOL CALL] search_alternate_flights({"origin":"ORD", "destination":"SEA", "date":"2024-06-17", "cabin":"Economy"})

[TOOL RESULT] {
  "flights": [
    {
      "flight_id": "AS207",
      "flight_number": "AS207",
      "departure": "08:30",
      "arrival": "11:03",
      "seats_available": 7,
      "fare_difference": 35
    },
    {
      "flight_id": "AS209",
      "flight_number": "AS209",
      "departure": "12:15",
      "arrival": "14:48",
      "seats_available": 4,
      "fare_difference": 0
    }
  ]
}

Here are the earlier flight options available from Chicago to Seattle on June 17th:

1. AS207 – Departs at 08:30, arrives at 11:03. Fare difference: $35.
2. AS209 – Departs at 12:15, arrives at 14:48. No fare difference.

A change fee of $75 applies for your Economy fare. If you select AS207, your total cost to change will be $75 + $35 (fare difference); for AS209, just the $75 change fee.

Would you like to proceed with rebooking to one of these flights? If so, please confirm the flight you prefer, and for your security, provide either the last 4 digits of the payment card used or your date of birth....
  [user] I'll go with the AS209 flight that leaves at 12:15. My date of birth is March 22, 1986. Can you confirm the total fee and the new flight details before you rebook?...
  [assistant] Thank you for confirming your choice and providing your date of birth. Here’s a summary before I proceed with the change:

**New flight selection**
- Flight: AS209
- Departure: 12:15 from Chicago O’Hare (ORD)
- Arrival: 14:48 in Seattle (SEA)
- Fare difference: $0
- Change fee: $75
- Total cost for the change: $75

Your checked baggage and other reservation details will transfer automatically to this new flight if you proceed.

To finalize the change, I’ll need to verify your identity.

[TOOL CALL] verify_identity({"pnr": "YK4J2M", "last_name": "Patel", "date_of_birth": "1986-03-22"})

[TOOL RESULT] {"result": "pass"}

Thank you, your identity is verified. Ready to proceed with rebooking you to flight AS209 for a $75 change fee. Shall I go ahead and make this change?...
  [user] Yes, please go ahead and make the change to AS209. Thanks for confirming everything—just let me know once it’s done....
  [assistant] Thank you for your confirmation! I’ll process your rebooking to flight AS209 now.

[TOOL CALL] rebook_flight({"pnr": "YK4J2M", "new_flight_id": "AS209"})

[TOOL RESULT] {
  "new_pnr": "YK4J2M",
  "passengers": [
    {"passenger_id": "P1", "first_name": "Amit", "last_name": "Patel"}
  ],
  "flight": {
    "flight_number": "AS209",
    "departure": "2024-06-17T12:15",
    "arrival": "2024-06-17T14:48",
    "origin": "ORD",
    "destination": "SEA"
  },
  "change_fee_charged": 75,
  "fare_difference_charged": 0,
  "ticket_status": "ACTIVE"
}

Your reservation has been successfully changed. Here are your updated details:

- Flight: AS209
- Departure: June 17th, 12:15 PM from Chicago O’Hare (ORD)
- Arrival: June 17th, 2:48 PM in Seattle (SEA)
- Change fee charged: $75 (no additional fare difference)
- Booking reference remains YK4J2M

All other reservation details, including your checked baggage, remain the same.


## Initialize UserCoherenceEvaluator

Configure the evaluator with an Azure OpenAI model deployment.

In [ ]:
# Read Azure OpenAI config from environment (loaded from .env above)
AZURE_OPENAI_ENDPOINT = os.environ.get("AZURE_OPENAI_ENDPOINT", "")
AZURE_OPENAI_API_KEY = os.environ.get("AZURE_OPENAI_API_KEY", "")
AZURE_OPENAI_API_VERSION = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-12-01-preview")
AZURE_OPENAI_DEPLOYMENT = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1")

print(f"Endpoint: {AZURE_OPENAI_ENDPOINT}")
print(f"Deployment: {AZURE_OPENAI_DEPLOYMENT}")
print(f"API version: {AZURE_OPENAI_API_VERSION}")
print(f"API key: {'***' + AZURE_OPENAI_API_KEY[-4:] if AZURE_OPENAI_API_KEY else '(not set)'}")

In [ ]:
from azure.ai.evaluation import AzureOpenAIModelConfiguration
from azure.identity import DefaultAzureCredential

model_config = AzureOpenAIModelConfiguration(
    azure_endpoint=AZURE_OPENAI_ENDPOINT,
    azure_deployment=AZURE_OPENAI_DEPLOYMENT,
    api_key=AZURE_OPENAI_API_KEY,
    api_version=AZURE_OPENAI_API_VERSION,
)

credential = DefaultAzureCredential()

evaluator = UserCoherenceEvaluator(model_config=model_config, credential=credential)
print("UserCoherenceEvaluator initialized")

Class UserCoherenceEvaluator: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.

UserCoherenceEvaluator initialized

## Run Evaluation Per Conversation

For each agent, evaluate every conversation independently and collect results.

In [10]:
import time

all_results = {}  # agent_name -> list of result dicts

for agent_name, convs in datasets.items():
    print(f"\n{'='*80}")
    print(f"Evaluating: {agent_name} ({len(convs)} conversations)")
    print(f"{'='*80}")

    agent_results = []

    for i, conv in enumerate(convs):
        conv_id = conv["conversation_id"]
        raw_messages = conv["messages"]

        # Reverse to chronological order (API returns newest-first), then normalize
        messages = normalize_trace_messages(list(reversed(raw_messages)))

        if len(messages) < 2:
            print(f"  [{i+1}/{len(convs)}] {conv_id[:30]}... SKIPPED (only {len(messages)} messages)")
            continue

        print(f"  [{i+1}/{len(convs)}] {conv_id[:30]}... ({len(messages)} messages)", end="")

        try:
            # Evaluate using the conversation input format
            result = evaluator(conversation={"messages": messages})
            score = result.get("user_coherence", float("nan"))
            per_step = result.get("user_coherence_per_step", [])
            print(f" -> score={score:.2f} ({len(per_step)} steps)")

            agent_results.append({
                "conversation_id": conv_id,
                "agent_name": agent_name,
                "num_messages": len(messages),
                "user_coherence": score,
                "per_step_scores": per_step,
                "total_tokens": result.get("user_coherence_total_tokens", 0),
                "model": result.get("user_coherence_model", ""),
            })
        except Exception as e:
            print(f" -> ERROR: {e}")
            agent_results.append({
                "conversation_id": conv_id,
                "agent_name": agent_name,
                "num_messages": len(messages),
                "user_coherence": float("nan"),
                "error": str(e),
            })

        # Small delay to avoid rate limiting
        time.sleep(0.5)

    all_results[agent_name] = agent_results
    print(f"\n  Completed {len(agent_results)} evaluations for {agent_name}")

================================================================================
Evaluating: legal-contract-review-sim (20 conversations)
================================================================================
  [1/20] conv_f77aa9489231d2c000qnNW5b8... (10 messages) -> score=2.00 (5 steps)
  [2/20] conv_ec319379ae2a86f200K0O0Fkh... (12 messages) -> score=2.00 (6 steps)
  [3/20] conv_b09635d5925bbf7a00FRGdvPZ... (12 messages) -> score=2.00 (6 steps)
  [4/20] conv_7b72c23198af6b5700N8yPmku... (10 messages) -> score=2.00 (5 steps)
  [5/20] conv_548358c9f3e8b85700xZukrtt... (13 messages) -> score=2.00 (6 steps)
  [6/20] conv_bb91bfbd599f7a2400w14I3u8... (10 messages) -> score=2.00 (5 steps)
  [7/20] conv_8685469b8f0655ea00e9DPuaJ... (12 messages) -> score=2.00 (6 steps)
  [8/20] conv_52dd8ae56c9c08d200zpbeHfC... (13 messages) -> score=2.00 (6 steps)
  [9/20] conv_a9b88a9fdc7891cc00C6i1N2Q... (10 messages) -> score=2.00 (5 steps)
  [10/20] conv_83ecc78a59e5184500fhb3PDR... (13 messages) -> score=2.00 (6 steps)
  [11/20] conv_cd82c5f00ab03d4f00T5mKPUK... (10 messages) -> score=2.00 (5 steps)
  [12/20] conv_f416e980089e4461004Kfd229... (12 messages) -> score=2.00 (6 steps)
  [13/20] conv_a3e20051918111a400XuYPFTf... (8 messages) -> score=2.00 (4 steps)
  [14/20] conv_d8782e4d1d39fc8700smeOEDS... (10 messages) -> score=2.00 (5 steps)
  [15/20] conv_14077dc4c8a8efe900e4tSdlG... (11 messages) -> score=2.00 (5 steps)
  [16/20] conv_5795a63fb03a6ba200GFfJpdW... (12 messages) -> score=2.00 (6 steps)
  [17/20] conv_e32c407ab24c3d4c00oSAXqne... (10 messages) -> score=2.00 (5 steps)
  [18/20] conv_5c801536d2fff1a300MtGZgs5... (12 messages) -> score=2.00 (6 steps)
  [19/20] conv_ca5b3161ed524cdd004PaR0Vy... (10 messages) -> score=2.00 (5 steps)
  [20/20] conv_71f856ef8cc712d300I3jUjVq... (4 messages) -> score=2.00 (2 steps)

  Completed 20 evaluations for legal-contract-review-sim

================================================================================
Evaluating: airline-customer-service-sim (30 conversations)
================================================================================
  [1/30] conv_90b677c1b52c2aaa002Jy9lpF... (8 messages) -> score=2.00 (4 steps)
  [2/30] conv_83ed527d93b557e700Pq8X0C5... (8 messages) -> score=2.00 (4 steps)
  [3/30] conv_8decba6f597c748a004Ojo7SI... (8 messages) -> score=2.00 (4 steps)
  [4/30] conv_96d221abc4d8f36300oedrXN6... (14 messages) -> score=2.00 (7 steps)
  [5/30] conv_fba1689acf4a9b9700JKnZzD0... (8 messages) -> score=2.00 (4 steps)
  [6/30] conv_05de0be8304ea52e00KzdHT8L... (14 messages) -> score=2.00 (7 steps)
  [7/30] conv_c25a99a749b6b69000V3brZuW... (14 messages) -> score=2.00 (7 steps)
  [8/30] conv_aaa3bb18c933123d00iSLM5Cs... (8 messages) -> score=2.00 (4 steps)
  [9/30] conv_1ba8c189be52254600XovYN3G... (8 messages) -> score=2.00 (4 steps)
  [10/30] conv_8345462fadd6dc6600cRMRSmd... (10 messages) -> score=2.00 (5 steps)
  [11/30] conv_f121d2baf2ff9cb8007Yuxe5r... (8 messages) -> score=2.00 (4 steps)
  [12/30] conv_2cf3f253f6cf7efd00KXkjgUd... (8 messages) -> score=2.00 (4 steps)
  [13/30] conv_0aab7892f9f6fc4600eCvkn11... (12 messages) -> score=2.00 (6 steps)
  [14/30] conv_f72e69fd1c0f37b500Ayrp5Wm... (8 messages) -> score=2.00 (4 steps)
  [15/30] conv_31ef5e3275c18dc3002zmHtZ5... (8 messages) -> score=2.00 (4 steps)
  [16/30] conv_1b255d874727afda00DY7bcSJ... (10 messages) -> score=1.50 (5 steps)
  [17/30] conv_97a455dc7d5c69e700W5ppvNm... (8 messages) -> score=2.00 (4 steps)
  [18/30] conv_06e583d8b78c1e2800ubKcEXf... (8 messages) -> score=2.00 (4 steps)
  [19/30] conv_8bef2b145fdecaf700e0QWWN9... (10 messages) -> score=2.00 (5 steps)
  [20/30] conv_c7e5c998b18bda5600MbdcCR1... (10 messages) -> score=2.00 (5 steps)
  [21/30] conv_8d9025084532f2680085pR6bb... (10 messages) -> score=2.00 (5 steps)
  [22/30] conv_092a2317ea12440c00DeuIoGR... (10 messages) -> score=2.00 (5 steps)
  [23/30] conv_c7444574c21929f300ZuNdfkv... (10 messages) -> score=2.00 (5 steps)
  [24/30] conv_815cb625f990cba000aH2Iwrm... (8 messages) -> score=2.00 (4 steps)
  [25/30] conv_6f956a6ca699ba3000LN2fhpq... (10 messages) -> score=2.00 (5 steps)
  [26/30] conv_159f7026eeed0a4c005L71QBj... (8 messages) -> score=2.00 (4 steps)
  [27/30] conv_5c054c1317b0b43200vheLmcR... (8 messages) -> score=2.00 (4 steps)
  [28/30] conv_758f6edb71c4db6300Rcr0h6N... (14 messages) -> score=2.00 (5 steps)
  [29/30] conv_29fdac0ce18c25d100HRvT68u... (8 messages) -> score=2.00 (4 steps)
  [30/30] conv_e6154d2e56ac1bef00jQZc76b... (8 messages) -> score=2.00 (4 steps)

  Completed 30 evaluations for airline-customer-service-sim

## Results Summary

Aggregate results per agent and display a summary table.

In [11]:
import math

# Build summary DataFrames
for agent_name, results in all_results.items():
    print(f"\n{'='*60}")
    print(f"Agent: {agent_name}")
    print(f"{'='*60}")

    df = pd.DataFrame([
        {
            "conversation_id": r["conversation_id"][:30] + "...",
            "messages": r["num_messages"],
            "user_coherence": r["user_coherence"],
            "tokens": r.get("total_tokens", 0),
        }
        for r in results
    ])

    display(df)

    valid_scores = [r["user_coherence"] for r in results if not math.isnan(r["user_coherence"])]
    if valid_scores:
        print(f"\n  Conversations evaluated: {len(valid_scores)}")
        print(f"  Mean user_coherence: {sum(valid_scores)/len(valid_scores):.3f}")
        print(f"  Min: {min(valid_scores):.2f}, Max: {max(valid_scores):.2f}")
        print(f"  Std: {pd.Series(valid_scores).std():.3f}")
    else:
        print("  No valid scores")

============================================================
Agent: legal-contract-review-sim
============================================================

                      conversation_id  messages  user_coherence  tokens
0   conv_f77aa9489231d2c000qnNW5b8...        10             2.0    6112
1   conv_ec319379ae2a86f200K0O0Fkh...        12             2.0    4376
2   conv_b09635d5925bbf7a00FRGdvPZ...        12             2.0    4716
3   conv_7b72c23198af6b5700N8yPmku...        10             2.0    4444
4   conv_548358c9f3e8b85700xZukrtt...        13             2.0    5171
5   conv_bb91bfbd599f7a2400w14I3u8...        10             2.0    4420
6   conv_8685469b8f0655ea00e9DPuaJ...        12             2.0    5525
7   conv_52dd8ae56c9c08d200zpbeHfC...        13             2.0    7766
8   conv_a9b88a9fdc7891cc00C6i1N2Q...        10             2.0   10250
9   conv_83ecc78a59e5184500fhb3PDR...        13             2.0    9542
10  conv_cd82c5f00ab03d4f00T5mKPUK...        10             2.0    5554
11  conv_f416e980089e4461004Kfd229...        12             2.0    5671
12  conv_a3e20051918111a400XuYPFTf...         8             2.0    6625
13  conv_d8782e4d1d39fc8700smeOEDS...        10             2.0    5134
14  conv_14077dc4c8a8efe900e4tSdlG...        11             2.0    7012
15  conv_5795a63fb03a6ba200GFfJpdW...        12             2.0    4886
16  conv_e32c407ab24c3d4c00oSAXqne...        10             2.0    4836
17  conv_5c801536d2fff1a300MtGZgs5...        12             2.0    7523
18  conv_ca5b3161ed524cdd004PaR0Vy...        10             2.0   10557
19  conv_71f856ef8cc712d300I3jUjVq...         4             2.0    4671

  Conversations evaluated: 20
  Mean user_coherence: 2.000
  Min: 2.00, Max: 2.00
  Std: 0.000

============================================================
Agent: airline-customer-service-sim
============================================================

                      conversation_id  messages  user_coherence  tokens
0   conv_90b677c1b52c2aaa002Jy9lpF...         8             2.0    3739
1   conv_83ed527d93b557e700Pq8X0C5...         8             2.0    3735
2   conv_8decba6f597c748a004Ojo7SI...         8             2.0    3399
3   conv_96d221abc4d8f36300oedrXN6...        14             2.0    4700
4   conv_fba1689acf4a9b9700JKnZzD0...         8             2.0    3143
5   conv_05de0be8304ea52e00KzdHT8L...        14             2.0    4164
6   conv_c25a99a749b6b69000V3brZuW...        14             2.0    4111
7   conv_aaa3bb18c933123d00iSLM5Cs...         8             2.0    3304
8   conv_1ba8c189be52254600XovYN3G...         8             2.0    3262
9   conv_8345462fadd6dc6600cRMRSmd...        10             2.0    3780
10  conv_f121d2baf2ff9cb8007Yuxe5r...         8             2.0    2952
11  conv_2cf3f253f6cf7efd00KXkjgUd...         8             2.0    3197
12  conv_0aab7892f9f6fc4600eCvkn11...        12             2.0    3902
13  conv_f72e69fd1c0f37b500Ayrp5Wm...         8             2.0    3495
14  conv_31ef5e3275c18dc3002zmHtZ5...         8             2.0    3810
15  conv_1b255d874727afda00DY7bcSJ...        10             1.5    3933
16  conv_97a455dc7d5c69e700W5ppvNm...         8             2.0    3438
17  conv_06e583d8b78c1e2800ubKcEXf...         8             2.0    3514
18  conv_8bef2b145fdecaf700e0QWWN9...        10             2.0    4237
19  conv_c7e5c998b18bda5600MbdcCR1...        10             2.0    3681
20  conv_8d9025084532f2680085pR6bb...        10             2.0    4345
21  conv_092a2317ea12440c00DeuIoGR...        10             2.0    4216
22  conv_c7444574c21929f300ZuNdfkv...        10             2.0    3461
23  conv_815cb625f990cba000aH2Iwrm...         8             2.0    3233
24  conv_6f956a6ca699ba3000LN2fhpq...        10             2.0    3850
25  conv_159f7026eeed0a4c005L71QBj...         8             2.0    2879
26  conv_5c054c1317b0b43200vheLmcR...         8             2.0    3257
27  conv_758f6edb71c4db6300Rcr0h6N...        14             2.0    3136
28  conv_29fdac0ce18c25d100HRvT68u...         8             2.0    3948
29  conv_e6154d2e56ac1bef00jQZc76b...         8             2.0    3599

  Conversations evaluated: 30
  Mean user_coherence: 1.983
  Min: 1.50, Max: 2.00
  Std: 0.091

## Per-Step Score Distribution

Visualize the distribution of per-step derail scores across all conversations for each agent.

In [13]:
from collections import Counter

for agent_name, results in all_results.items():
    print(f"\n{'='*60}")
    print(f"Agent: {agent_name} — Per-Step Score Distribution")
    print(f"{'='*60}")

    score_counts = Counter()
    total_steps = 0
    derailed_conversations = []

    for r in results:
        per_step = r.get("per_step_scores", [])
        for step in per_step:
            s = step.get("derail_score")
            if s is not None:
                score_counts[s] += 1
                total_steps += 1

        # Flag conversations with any score=0 (derailed)
        zeros = [step for step in per_step if step.get("derail_score") == 0]
        if zeros:
            derailed_conversations.append({
                "conversation_id": r["conversation_id"][:30] + "...",
                "derailed_steps": [
                    {"step": z.get("conversation_step"), "explanation": z.get("explanation", "")}
                    for z in zeros
                ],
            })

    print(f"\n  Total scored steps: {total_steps}")
    for score in [2, 1, 0]:
        count = score_counts.get(score, 0)
        pct = (count / total_steps * 100) if total_steps else 0
        bar = "█" * int(pct / 2)
        label = {2: "Likely/logical", 1: "Weak/possible", 0: "Not logical"}[score]
        print(f"  Score {score} ({label}): {count:3d} ({pct:5.1f}%) {bar}")

    if derailed_conversations:
        print(f"\n  Conversations with derailed steps (score=0):")
        for dc in derailed_conversations:
            print(f"    {dc['conversation_id']}")
            for ds in dc["derailed_steps"]:
                print(f"      Step {ds['step']}: {ds['explanation']}")

============================================================
Agent: legal-contract-review-sim — Per-Step Score Distribution
============================================================

  Total scored steps: 85
  Score 2 (Likely/logical):  85 (100.0%) ██████████████████████████████████████████████████
  Score 1 (Weak/possible):   0 (  0.0%)
  Score 0 (Not logical):   0 (  0.0%)

============================================================
Agent: airline-customer-service-sim — Per-Step Score Distribution
============================================================

  Total scored steps: 110
  Score 2 (Likely/logical): 109 ( 99.1%) █████████████████████████████████████████████████
  Score 1 (Weak/possible):   0 (  0.0%)
  Score 0 (Not logical):   1 (  0.9%)

  Conversations with derailed steps (score=0):
    conv_1b255d874727afda00DY7bcSJ...
      Step 3: The user repeats the exact same information and request as in the previous step, which does not logically follow after the agent already addressed these details.

## Save Results

Save the full evaluation results (including per-step details) to JSON files.

In [ ]:
for agent_name, results in all_results.items():
    output_file = f"{agent_name}_user_coherence_results.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"Saved {len(results)} results to {output_file}")

Saved 20 results to legal-contract-review-sim_user_coherence_results.json
Saved 30 results to airline-customer-service-sim_user_coherence_results.json