# User Coherence Evaluation on Foundry Agent Traces

Evaluates user coherence (derail detection) on multi-turn conversations fetched from Azure AI Foundry agents:
- **legal-contract-review-sim** (20 conversations)
- **airline-customer-service-sim** (30 conversations)

Each conversation is evaluated independently, producing per-step derail scores and an aggregate mean score.

In [10]:
import json
import os
import asyncio
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# All files (datasets, .env, results) live in the same directory as this notebook
load_dotenv()

# Import evaluator and trace normalizer
from azure.ai.evaluation._evaluators._user_coherence._user_coherence import (
    UserCoherenceEvaluator,
    normalize_trace_messages,
)

# Load datasets (produced by fetch_agent_conversations.py in the same folder)
AGENTS = os.environ.get("AGENTS", "legal-contract-review-sim,airline-customer-service-sim").split(",")

datasets = {}
for agent_name in AGENTS:
    filename = f"{agent_name}_conversations.json"
    if not Path(filename).exists():
        print(f"WARNING: {filename} not found — run fetch_agent_conversations.py first")
        continue
    with open(filename, encoding="utf-8") as f:
        datasets[agent_name] = json.load(f)
    print(f"Loaded {len(datasets[agent_name])} conversations for {agent_name}")

Loaded 50 conversations for legal-contract-review-sim
Loaded 50 conversations for airline-customer-service-sim

## Preview: Normalize Trace Messages

The raw trace messages from Foundry use `output_text`/`input_text` content types and include extra metadata. `normalize_trace_messages()` converts them to simple `{"role": ..., "content": ...}` dicts.

In [11]:
# Preview normalization on the first conversation of each agent
# NOTE: Foundry conversations are already in chronological order.
for agent_name, convs in datasets.items():
    raw_msgs = convs[0]["messages"]
    normalized = normalize_trace_messages(raw_msgs)
    print(f"\n=== {agent_name} (conversation {convs[0]['conversation_id']}) ===")
    print(f"Raw messages: {len(raw_msgs)}, Normalized: {len(normalized)}")
    for msg in normalized:
        print(f"  [{msg['role']}] {msg['content']}...")

=== legal-contract-review-sim (conversation conv_0842a7cbecd7e0cf00uPEBlTji4cRqO5iK5q7btmr4ZP5UGqVG) ===
Raw messages: 10, Normalized: 10
  [user] Hey, this is Olivia Mensah. Quick one — is the limitation-of-liability clause in this SaaS agreement ok? I need to sign today, so I really need a fast answer....
  [assistant] Hi Olivia! To properly assess the limitation-of-liability clause for your SaaS agreement, I need to know:

1. Which contract you’re referencing (contract_id or the agreement’s name).
2. What jurisdiction governs the contract (as some rules vary).
3. Any company policy specifics (for example, are uncapped liabilities always unacceptable?).

To review quickly, I’ll:
- Retrieve contract metadata for context,
- Locate and read the actual limitation-of-liability clause (not just the heading or search hits),
- Check if the clause aligns with your company policy and jurisdictional rules,
- Explain any material risks in plain language and propose fixes if needed.

Please provide the contract_id (or clarify which agreement), and I’ll get started right away....
  [user] It’s the Nimbus SaaS License Agreement, US law. I don’t have a contract ID handy — can you just check the limitation-of-liability section and tell me if I’m safe to sign? I’m really tight on time....
  [assistant] Understood, Olivia. I want to give you a responsible answer, but I need to make sure I’m checking the *actual* limitation-of-liability clause text—since this is a clause that can seriously affect your company’s risk if it’s drafted poorly.

Let me do the following:

1. List the clauses in the Nimbus SaaS License Agreement to pinpoint the limitation-of-liability section.
2. Retrieve and read the full clause text.
3. Quickly compare it to standard US SaaS precedent and (if available) your company’s policy.
4. Flag any risks in plain English and suggest clear changes if needed.

I’ll keep the review focused and brief. Starting now:

[TOOL CALL] list_clauses({"contract_id": "Nimbus_SaaS_License_Agreement"})

[TOOL RESULT]
{
  "clauses": [
    {"clause_id": "7.1", "heading": "Limitation of Liability", "page": 12},
    {"clause_id": "7.2", "heading": "Exclusion of Consequential Damages", "page": 13},
    {"clause_id": "6.4", "heading": "Indemnification", "page": 11},
    {"clause_id": "9.3", "heading": "Governing Law", "page": 16},
    // ... other clauses omitted for brevity
  ]
}

The limitation-of-liability clause is Section 7.1. Next, I’ll retrieve and review its full text.

[TOOL CALL] get_clause({"contract_id": "Nimbus_SaaS_License_Agreement", "clause_id": "7.1"})

[TOOL RESULT]
{
  "clause_id": "7.1",
  "heading": "Limitation of Liability",
  "text": "EXCEPT FOR LIABILITY ARISING FROM (A) BREACH OF SECTION 5 (CONFIDENTIALITY), (B) EITHER PARTY'S INDEMNIFICATION OBLIGATIONS UNDER SECTION 6.4, (C) CUSTOMER’S PAYMENT OBLIGATIONS, OR (D) EITHER PARTY'S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT, IN NO EVENT WILL EITHER PARTY’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNT PAID OR PAYABLE BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. THE FOREGOING LIMITATION WILL APPLY WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY.",
  "cross_references": ["Section 5", "Section 6.4"]
}

Here’s what this clause does, in plain English:
- **Caps liability**: Most damages for either party are capped at the fees paid in the last 12 months.
- **Exceptions (the cap does NOT apply to)**:
    - Breach of confidentiality (Section 5).
    - Either party’s indemnification obligations (Section 6.4 – likely for IP/third party claims).
    - Customer’s payment obligations.
    - Gross negligence or willful misconduct.

**Quick market/context check:**
- These exceptions are typical—capping liability for ordinary claims but not for confidentiality, indemnity, gross negligence, or payment.
- The cap amount (12 months’ fees) is market standard for US SaaS.

**Next steps** (optional for thoroughness; can skip if you’re truly out of time):
- If you want to see the exact company red-lines or compare to US precedent, let me know and I can pull that quickly.
- Otherwise: Based on this clause text and US SaaS market, this clause is balanced and not an outlier risk.

**Summary**:
Based on the clause language, this is a *standard, reasonable* limitation-of-liability clause for US SaaS agreements. It caps claims at 12 months’ fees, but carves out the most sensitive areas (confidentiality, indemnity, gross negligence, payment). This is widely accepted unless your company policy is stricter.

**Recommendation (not legal advice):**
You’re NOT exposed to uncapped liability for ordinary claims, and the exceptions are aligned with market practice. Unless your company prohibits this cap level or has special carve-outs, you are generally “safe to sign” from a liability cap perspective.

Let me know if you want a quick check against your company policy or want to see the referenced sections for completeness. Otherwise, you can sign with reasonable risk on this issue....
  [user] Thanks, that's helpful. But does that mean if there's a confidentiality breach or a data security incident, there's no cap at all? That feels risky — is that normal, or should I ask for a change?...
  [assistant] Great question, Olivia. Here’s how it works based on the clause text:

### What the Clause Means
- For “normal” contract claims (delays, service issues), each party’s total liability is capped at the last 12 months’ fees.
- **BUT**: The cap **does not apply** to claims involving:
  - Confidentiality breaches,
  - Indemnification obligations (often IP/third-party claims),
  - Your company’s payment obligations,
  - Gross negligence or willful misconduct.

**So yes:**
If there’s a confidentiality breach (including a significant data security incident, if it constitutes a breach of confidentiality), the party responsible could face **uncapped liability**—there’s no maximum dollar limit.

---

### Market Practice & Risk
- **Is this normal?**
  - Yes, it’s pretty common in the US SaaS market for confidentiality breaches, IP indemnity, and gross negligence to be excluded from liability caps—especially when sensitive data is involved.
  - The reasoning: Those breaches can cause huge, unpredictable damages (like regulatory fines, reputational harm, lawsuits), so customers want full recourse.
- **Is this risky for you?**
  - **For the vendor (SaaS provider):** There’s theoretically unlimited exposure if they mishandle data or disclose confidential info.
  - **For the customer:** You have leverage to hold the vendor fully responsible if there is a material confidentiality/data breach.

#### Should you ask for a change?
- **If you are the customer:** This is good protection for you—most customers *want* no cap on confidentiality/data-related claims.
- **If you are the vendor:** It's potentially risky; you may want to negotiate to place a higher-than-normal cap (like 2x or 3x fees) for confidentiality/data breaches, but not full uncapped liability. Still, many customers insist on the current arrangement.

---

### Recommendation

- **If your company is the SaaS customer:** This clause is market and favorable for you. No redlines needed unless your business wants to give the vendor extra protection (not typical).
- **If your company is the vendor:** Consider if you’re comfortable with uncapped liability for confidentiality/data breaches. If you want to propose a cap (e.g., 2x or 3x annual fees), I can suggest exact language.

**Let me know your position (customer or vendor), and if you want a sample redline to limit your liability for confidentiality breaches.** Or, if you approve, you’re set to sign as is....
  [user] We’re the vendor, so this is what I was worried about. I get why customers want protection, but we can’t take on unlimited risk for a data breach — that’s just not going to fly with our management. Can you give me a sample edit that would cap our liability for confidentiality and data security claims, but still be reasonable for the customer?...
  [assistant] Absolutely, Olivia—that’s a reasonable and common position for SaaS vendors. Many vendors propose a **higher cap** (often 2x or 3x the annual fees) for claims involving confidentiality or data breaches, instead of uncapped liability. This can balance customer concerns with your company’s risk appetite.

Here’s a tailored approach:

### What to Propose
- **Ordinary claims:** Still capped at 12 months’ fees.
- **Confidentiality and indemnity claims (including data breach):** Capped at a higher amount, such as 2x or 3x annual fees.
- **Gross negligence/willful misconduct:** May remain uncapped if the customer insists, but some vendors propose to cap everything.

---

### Sample Redline (Replacement Clause Text)

Here’s a concrete edit to Section 7.1:

**Original Excerpt**
> “...EXCEPT FOR LIABILITY ARISING FROM (A) BREACH OF SECTION 5 (CONFIDENTIALITY), (B) EITHER PARTY'S INDEMNIFICATION OBLIGATIONS UNDER SECTION 6.4, ... IN NO EVENT WILL EITHER PARTY’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNT PAID OR PAYABLE BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. ...”

**Proposed Redline**
> “...EXCEPT FOR LIABILITY ARISING FROM (A) BREACH OF SECTION 5 (CONFIDENTIALITY) OR (B) EITHER PARTY'S INDEMNIFICATION OBLIGATIONS UNDER SECTION 6.4, IN NO EVENT WILL EITHER PARTY’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT EXCEED THE TOTAL AMOUNT PAID OR PAYABLE BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
>
> NOTWITHSTANDING THE FOREGOING, EACH PARTY'S TOTAL LIABILITY FOR CLAIMS ARISING FROM (A) ITS BREACH OF SECTION 5 (CONFIDENTIALITY) OR (B) ITS INDEMNIFICATION OBLIGATIONS UNDER SECTION 6.4, SHALL NOT EXCEED THREE (3) TIMES THE TOTAL AMOUNTS PAID OR PAYABLE BY CUSTOMER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
>
> THE FOREGOING LIMITATIONS SHALL NOT APPLY TO LIABILITY RESULTING FROM EITHER PARTY'S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT, OR TO CUSTOMER’S PAYMENT OBLIGATIONS.”

---

### Plain-Language Summary
- Most claims: limited to 12 months’ fees.
- Confidentiality/data/security & indemnification claims:** capped at 3x annual fees (you can adjust to 2x or your internal comfort level).
- Truly egregious conduct (gross negligence/willful misconduct): still uncapped if required.
- Customer’s payment obligations: not limited.

---

### Implementation Note
- Make sure to call out "confidentiality" and data-related breaches together, if Section 5 includes data security.
- Adjust “three (3) times” to “two (2) times” if your internal policy prefers.

**Would you like to see boilerplate similar language used in US SaaS contracts, or does this draft work for you? Let me know if you want a cut-and-paste version with defined terms, or if you have other carve-outs or internal policies.**...
  [user] This is exactly what I needed, thank you! The sample language is clear and I can use that as a starting point for our legal review. No need for more boilerplate right now. Appreciate the quick turnaround — I can take it from here....
  [assistant] You're very welcome, Olivia! I'm glad the sample language was helpful and you're set for your internal review. If you need a quick look at other key clauses—or need plain language explanations for anything tricky—just let me know anytime.

Good luck with the negotiations and signing. If anything else comes up, reach out and I'll help as promptly as before.

[END]...

=== airline-customer-service-sim (conversation conv_b4dd30d64e6b0dc300V6yB6BNUA1aQcaiGB4cIM2EPiTtvxrlP) ===
Raw messages: 10, Normalized: 10
  [user] Hey, this is Olivia Martinez. My flight today was delayed for hours because of weather and now I want a full cash refund. Weather is your problem, not mine....
  [assistant] I’m sorry to hear about the disruption to your travel plans, Olivia. I understand how frustrating delays can be, especially due to weather.

To review your eligibility and assist you with a refund request, could you please provide one of the following:
- Your 6-character booking reference (PNR), or
- Your flight number and date of travel

If you have the booking reference handy, that’s quickest. Otherwise, I can look up your reservation using your last name, flight number, and today’s date.

Once I’ve located your reservation, I’ll review the specific fare rules and the circumstances of your delay, and explain your options....
  [user] I don’t have the booking code in front of me, but the flight was 6123 from Dallas to Chicago today. Name is Olivia Martinez. I just want my money back....
  [assistant] Thank you for providing your flight details, Olivia. I’ll first locate your reservation, then review the fare rules and the situation with your flight so I can clearly advise on refund eligibility.

[TOOL CALL] lookup_reservation(last_name="Martinez", flight_number="6123", date="2024-06-12")
[TOOL RESULT] {
  "pnr": "F9K1LQ",
  "passengers": [
    {
      "name": "Olivia Martinez",
      "passenger_id": "001"
    }
  ],
  "flights": [
    {
      "flight_number": "6123",
      "origin": "DFW",
      "destination": "ORD",
      "scheduled_departure": "2024-06-12T12:10",
      "actual_departure": "2024-06-12T17:50",
      "status": "Delayed",
      "fare_class": "Economy"
    }
  ],
  "ticket_status": "Issued",
  "baggage": {
    "checked": 1,
    "status": "Loaded"
  }
}

Now I’ll confirm both your fare rules and the specifics of today’s flight delay.

[TOOL CALL] get_fare_rules(pnr="F9K1LQ")
[TOOL RESULT] {
  "fare_class": "Economy",
  "refundable": true,
  "refund_type": "Credit",
  "changeable": true,
  "change_fee": 100,
  "restrictions": ["Refunds provided as travel credit unless schedule change exceeds 2 hours or flight is cancelled."]
}

[TOOL CALL] get_flight_status(flight_number="6123", date="2024-06-12")
[TOOL RESULT] {
  "flight_number": "6123",
  "date": "2024-06-12",
  "scheduled_departure": "2024-06-12T12:10",
  "actual_departure": "2024-06-12T17:50",
  "status": "Delayed",
  "delay_reason": "Weather",
  "delay_duration_minutes": 340
}

Thanks for your patience. Here’s a quick summary:
- Your flight (6123, Dallas to Chicago) was delayed by 5 hours and 40 minutes due to weather.
- You booked an Economy ticket. Normally, refunds are given as travel credits unless a schedule change is over 2 hours (which yours was).

Even though the cause was weather, our policy allows a full cash refund for delays over 2 hours, regardless of fare type. I’ll just need to verify your identity before proceeding.

Could you please provide either:
- The last 4 digits of the payment card you used, or
- Your date of birth

Once I verify your identity, I’ll initiate the cash refund for your flight....
  [user] Yeah, my card ends in 4492. And just to be totally clear, I want an actual cash refund, not some credit. I lost a whole day because of this mess....
  [assistant] Thank you for confirming the last four digits of your card, Olivia. I completely understand—you are eligible for a cash refund given the significant delay, and I’ll make sure we process it accordingly.

First, let me verify your identity and then initiate the cash refund.

[TOOL CALL] verify_identity(pnr="F9K1LQ", last_name="Martinez", last_4_of_payment="4492")
[TOOL RESULT] {"result": "pass"}

Now, I’ll process the cash refund for your delayed flight.

[TOOL CALL] issue_refund(pnr="F9K1LQ", amount=285, reason="Cash refund due to delay over 2 hours (5hr40min) on 6123")
[TOOL RESULT] {"refund_id": "RF0098877", "amount": 285, "status": "Success"}

Your identity is verified and your cash refund of $285 is being processed due to the over-2-hour delay on your flight. The refund will be credited back to your original payment method, and you should see the amount in your account within 7–10 business days (timing depends on your card issuer).

Is there anything else I can help you with today regarding this booking or any other travel issue?...
  [user] Alright, thanks for processing that. I just want to confirm—this is an actual cash refund, not a voucher or travel credit, right? I don’t want a credit, just my money back....
  [assistant] Yes, I can confirm: this is a cash refund, not a voucher or travel credit. Your refund of $285 is being returned directly to your original payment card ending in 4492. You will not receive a travel credit or voucher—just the cash back.

If you have any further questions or need assistance with anything else, let me know. Otherwise, thank you for your patience, and I’m sorry again for the inconvenience you experienced. Safe travels in the future, Olivia....
  [user] Okay, thanks for confirming. I’ll keep an eye on my account for the refund. That’s all I needed....
  [assistant] You’re very welcome, Olivia. I appreciate your patience and understanding. If you need any further assistance in the future, feel free to reach out. Wishing you smoother travels next time!

[END]...

## Initialize UserCoherenceEvaluator

Configure the evaluator with an Azure OpenAI model deployment.

In [12]:
# Read Azure OpenAI config from environment (loaded from .env above)
AZURE_OPENAI_ENDPOINT = os.environ.get("AZURE_OPENAI_ENDPOINT", "")
AZURE_OPENAI_API_KEY = os.environ.get("AZURE_OPENAI_API_KEY", "")
AZURE_OPENAI_API_VERSION = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-12-01-preview")
AZURE_OPENAI_DEPLOYMENT = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1")

print(f"Endpoint: {AZURE_OPENAI_ENDPOINT}")
print(f"Deployment: {AZURE_OPENAI_DEPLOYMENT}")
print(f"API version: {AZURE_OPENAI_API_VERSION}")
print(f"API key: {'***' + AZURE_OPENAI_API_KEY[-4:] if AZURE_OPENAI_API_KEY else '(not set)'}")

Endpoint: https://eval-cairo-ai-foundry-eus.cognitiveservices.azure.com/
Deployment: gpt-4.1
API version: 2024-12-01-preview
API key: ***hlhF

In [13]:
from azure.ai.evaluation import AzureOpenAIModelConfiguration
from azure.identity import DefaultAzureCredential

model_config = AzureOpenAIModelConfiguration(
    azure_endpoint=AZURE_OPENAI_ENDPOINT,
    azure_deployment=AZURE_OPENAI_DEPLOYMENT,
    api_key=AZURE_OPENAI_API_KEY,
    api_version=AZURE_OPENAI_API_VERSION,
)

credential = DefaultAzureCredential()

evaluator = UserCoherenceEvaluator(model_config=model_config, credential=credential)
print("UserCoherenceEvaluator initialized")

UserCoherenceEvaluator initialized

## Run Evaluation Per Conversation

For each agent, evaluate every conversation independently and collect results.

In [14]:
import time

all_results = {}  # agent_name -> list of result dicts

for agent_name, convs in datasets.items():
    print(f"\n{'='*80}")
    print(f"Evaluating: {agent_name} ({len(convs)} conversations)")
    print(f"{'='*80}")

    agent_results = []

    for i, conv in enumerate(convs):
        conv_id = conv["conversation_id"]
        raw_messages = conv["messages"]

        # Normalize (messages are already in chronological order)
        messages = normalize_trace_messages(raw_messages)

        if len(messages) < 2:
            print(f"  [{i+1}/{len(convs)}] {conv_id[:30]}... SKIPPED (only {len(messages)} messages)")
            continue

        print(f"  [{i+1}/{len(convs)}] {conv_id[:30]}... ({len(messages)} messages)", end="")

        try:
            # Evaluate using the conversation input format
            result = evaluator(conversation={"messages": messages})
            score = result.get("user_coherence", float("nan"))
            per_step = result.get("user_coherence_per_step", [])
            print(f" -> score={score:.2f} ({len(per_step)} steps)")

            agent_results.append({
                "conversation_id": conv_id,
                "agent_name": agent_name,
                "num_messages": len(messages),
                "user_coherence": score,
                "per_step_scores": per_step,
                "total_tokens": result.get("user_coherence_total_tokens", 0),
                "model": result.get("user_coherence_model", ""),
            })
        except Exception as e:
            print(f" -> ERROR: {e}")
            agent_results.append({
                "conversation_id": conv_id,
                "agent_name": agent_name,
                "num_messages": len(messages),
                "user_coherence": float("nan"),
                "error": str(e),
            })

        # Small delay to avoid rate limiting
        time.sleep(0.5)

    all_results[agent_name] = agent_results
    print(f"\n  Completed {len(agent_results)} evaluations for {agent_name}")

================================================================================
Evaluating: legal-contract-review-sim (50 conversations)
================================================================================
  [1/50] conv_0842a7cbecd7e0cf00uPEBlTj... (10 messages) -> score=2.00 (5 steps)
  [2/50] conv_c43ff32bd5c4f0f800gDkl0Wz... (10 messages) -> score=2.00 (5 steps)
  [3/50] conv_8d4b2d823e8a1d2100HK9q8gZ... (10 messages) -> score=2.00 (5 steps)
  [4/50] conv_a52d0cd1505aa0920098fmBAk... (10 messages) -> score=2.00 (5 steps)
  [5/50] conv_a2650e815ac77d7d00sjZYSMb... (10 messages) -> score=2.00 (5 steps)
  [6/50] conv_5844bba372c6c36f00wFpFAQQ... (11 messages) -> score=2.00 (5 steps)
  [7/50] conv_3b52bf7f44771fe400lXmmUqE... (9 messages) -> score=2.00 (4 steps)
  [8/50] conv_7d4e3ef070b0583c00bekHSCL... (8 messages) -> score=2.00 (4 steps)
  [9/50] conv_7309955b0d21b1d400p14ZoDT... (8 messages) -> score=2.00 (4 steps)
  [10/50] conv_f064f710eb0666b800Iv1UBib... (10 messages) -> score=2.00 (5 steps)
  [11/50] conv_4dd34510dd1753f6003QwF4Ot... (11 messages) -> score=2.00 (5 steps)
  [12/50] conv_df1c9b1bbf35a8cc00vsHQm0s... (10 messages) -> score=2.00 (5 steps)
  [13/50] conv_ce3d8ef424fb59f400LBSnYtH... (12 messages) -> score=2.00 (6 steps)
  [14/50] conv_b0177754bb0366d400N8uT3fD... (10 messages) -> score=2.00 (5 steps)
  [15/50] conv_f137285354cd0abd00Fw1NITi... (12 messages) -> score=2.00 (6 steps)
  [16/50] conv_4346b89a2062620a00yefxPIP... (10 messages) -> score=2.00 (5 steps)
  [17/50] conv_6c7ff3c0fcfcd45300ZHAkgCb... (10 messages) -> score=2.00 (5 steps)
  [18/50] conv_bd1ce398f7b23db70058mU0dO... (8 messages) -> score=2.00 (4 steps)
  [19/50] conv_dae72f5e231910a800Pa8K76r... (8 messages) -> score=2.00 (4 steps)
  [20/50] conv_5c49a5f5d167d50500tpXam6g... (8 messages) -> score=2.00 (4 steps)
  [21/50] conv_091d7a5f3d767a5200PJuXlTT... (10 messages) -> score=2.00 (5 steps)
  [22/50] conv_0f94e0cfd39b257b00uHlJwJS... (13 messages) -> score=2.00 (6 steps)
  [23/50] conv_6ad29d39b891ca5100KhgL3tK... (10 messages) -> score=2.00 (5 steps)
  [24/50] conv_7f53f6b392b7e67600j8MPraI... (10 messages) -> score=2.00 (5 steps)
  [25/50] conv_7b665a69c2b4419900az2VP22... (8 messages) -> score=2.00 (4 steps)
  [26/50] conv_61b3fb35b27b2d0500FHbTrmA... (13 messages) -> score=2.00 (6 steps)
  [27/50] conv_819771956b847c5700LzWrvjm... (11 messages) -> score=2.00 (5 steps)
  [28/50] conv_99bbc2dba2c24db100HRVjYmn... (10 messages) -> score=2.00 (5 steps)
  [29/50] conv_ee4f4fda424d6cc400IjP4tR0... (11 messages) -> score=2.00 (5 steps)
  [30/50] conv_df8193ed23a25c1200zIOjB1w... (10 messages) -> score=2.00 (5 steps)
  [31/50] conv_d83f9b8363196b0e00f7ej968... (12 messages) -> score=2.00 (6 steps)
  [32/50] conv_999652fcbf311f3f00fL3BBFl... (10 messages) -> score=2.00 (5 steps)
  [33/50] conv_7a1d62deaf729bcb00masxGIE... (13 messages) -> score=2.00 (6 steps)
  [34/50] conv_2e9213ad12e0c99300O9nmtsk... (10 messages) -> score=2.00 (5 steps)
  [35/50] conv_3b3517b1d014029600zoN09yp... (10 messages) -> score=2.00 (5 steps)
  [36/50] conv_c89b39972733ce0600S9nCfZQ... (10 messages) -> score=2.00 (5 steps)
  [37/50] conv_1c37d407f98cdec600iNOSllp... (10 messages) -> score=2.00 (5 steps)
  [38/50] conv_703955bd31cc759a00kCSuMd2... (10 messages) -> score=2.00 (5 steps)
  [39/50] conv_a67487def52f364400TBz043t... (12 messages) -> score=2.00 (6 steps)
  [40/50] conv_d7f6d586e422413b00o0oRGRZ... (10 messages) -> score=2.00 (5 steps)
  [41/50] conv_2dd77c2c7a8337b6001bEhVP1... (10 messages) -> score=2.00 (5 steps)
  [42/50] conv_a7c84f31481c17e5002q6Chi5... (11 messages) -> score=2.00 (5 steps)
  [43/50] conv_4f80efde464a376200vhL6InT... (6 messages) -> score=2.00 (3 steps)
  [44/50] conv_a414274f0fe62d2900xXEfXzt... (6 messages) -> score=2.00 (3 steps)
  [45/50] conv_f8e3cc4fd26ff27000dob3B4f... (8 messages) -> score=2.00 (4 steps)
  [46/50] conv_2a8225c918083612004OQvvrm... (10 messages) -> score=2.00 (5 steps)
  [47/50] conv_d2818f234d162edc00jjhyEiC... (10 messages) -> score=2.00 (5 steps)
  [48/50] conv_4ab42f1ea7a4884000CsIriO3... (8 messages) -> score=2.00 (4 steps)
  [49/50] conv_e97a0580bd35af36000AEgc4x... (10 messages) -> score=2.00 (5 steps)
  [50/50] conv_ccb55e868b89dc6a00NdIhjeR... (10 messages) -> score=2.00 (5 steps)

  Completed 50 evaluations for legal-contract-review-sim

================================================================================
Evaluating: airline-customer-service-sim (50 conversations)
================================================================================
  [1/50] conv_b4dd30d64e6b0dc300V6yB6BN... (10 messages) -> score=2.00 (5 steps)
  [2/50] conv_06b3877fbbeca15200ZMTAGL9... (15 messages) -> score=2.00 (7 steps)
  [3/50] conv_84f6392575738eba00kqxeUlq... (14 messages) -> score=2.00 (7 steps)
  [4/50] conv_4b0a422287a2e5cb00PtEbvVz... (17 messages) -> score=2.00 (8 steps)
  [5/50] conv_c2385265a03d6fba00eGzsnQB... (14 messages) -> score=2.00 (7 steps)
  [6/50] conv_eb3c9f2328e4671d00RC5hJ04... (15 messages) -> score=2.00 (7 steps)
  [7/50] conv_ce490d3bf1b340e00071ZcwPo... (13 messages) -> score=2.00 (6 steps)
  [8/50] conv_6341b1140363451400dpZZEIX... (10 messages) -> score=2.00 (5 steps)
  [9/50] conv_54d29dbaf3d92b3800UlavsFp... (14 messages) -> score=2.00 (7 steps)
  [10/50] conv_064412c823b1ad0b00gCO1sEj... (17 messages) -> score=2.00 (8 steps)
  [11/50] conv_7ac6d01371e75aa100dwgPblZ... (10 messages) -> score=2.00 (5 steps)
  [12/50] conv_d33fe3b9ffa296050001mzCiV... (10 messages) -> score=2.00 (5 steps)
  [13/50] conv_3139403df8a7a65700YVUKPx1... (8 messages) -> score=2.00 (4 steps)
  [14/50] conv_6a9f27df9fee4dc000iSeHHYT... (8 messages) -> score=2.00 (4 steps)
  [15/50] conv_cca7fae6ade4edf7004mUjm96... (8 messages) -> score=2.00 (4 steps)
  [16/50] conv_26f4905bc3b22f6b00t99AacL... (10 messages) -> score=2.00 (5 steps)
  [17/50] conv_675268409258dad100z8EAWXl... (10 messages) -> score=2.00 (5 steps)
  [18/50] conv_c478f6e0705f5bb300sGo52FE... (10 messages) -> score=2.00 (5 steps)
  [19/50] conv_6dd38d9ab2b2c13700yvtl3od... (8 messages) -> score=2.00 (4 steps)
  [20/50] conv_b925dc46d1f2dad400U6Ezk9Z... (10 messages) -> score=2.00 (5 steps)
  [21/50] conv_087adc3b102d1b4800SQhtupW... (12 messages) -> score=2.00 (6 steps)
  [22/50] conv_2fbca287fc50b7fc00nLcPSnX... (12 messages) -> score=2.00 (6 steps)
  [23/50] conv_f4e7e11b1db00c6a00MI6S78r... (17 messages) -> score=2.00 (8 steps)
  [24/50] conv_90b3666b17095e5900LLAhzZe... (12 messages) -> score=2.00 (6 steps)
  [25/50] conv_01b60d72463e956800r5t8JRW... (12 messages) -> score=2.00 (6 steps)
  [26/50] conv_485e96aa3edd859d0035jHcex... (10 messages) -> score=2.00 (5 steps)
  [27/50] conv_f39d463408b9916a00kK3eeU9... (14 messages) -> score=2.00 (7 steps)
  [28/50] conv_a325abdfa6ef95c300F4kWx74... (14 messages) -> score=2.00 (7 steps)
  [29/50] conv_b802f521b498b1dd00ckUFk7b... (12 messages) -> score=2.00 (6 steps)
  [30/50] conv_98de85b4e7e5d05100wwwuxMx... (16 messages) -> score=2.00 (8 steps)
  [31/50] conv_6f35fe661e5d8a6300If1bwqt... (14 messages) -> score=2.00 (7 steps)
  [32/50] conv_e0e1348e93b022ca008It33YZ... (12 messages) -> score=2.00 (6 steps)
  [33/50] conv_6bdc7f991ed5bfa400XRkLBqx... (14 messages) -> score=2.00 (7 steps)
  [34/50] conv_111c15ff83716cc600COHmNvl... (14 messages) -> score=2.00 (7 steps)
  [35/50] conv_3245e7ab86535f6800enP0Hdz... (16 messages) -> score=2.00 (8 steps)
  [36/50] conv_598dd3d42653ed0300qJ1Izvg... (13 messages) -> score=2.00 (6 steps)
  [37/50] conv_87f559256e3b1d3900wpcik16... (14 messages) -> score=2.00 (7 steps)
  [38/50] conv_e345bd64382740fc00NhegzB5... (15 messages) -> score=2.00 (7 steps)
  [39/50] conv_6f8682b842b85bb900GuqTXEY... (16 messages) -> score=2.00 (8 steps)
  [40/50] conv_b9b0b4297656ef8800hmovdiP... (12 messages) -> score=2.00 (6 steps)
  [41/50] conv_a509881dd413e5e700AHN5A9l... (9 messages) -> score=2.00 (4 steps)
  [42/50] conv_c32dc578676cf11c00YIq7oaH... (10 messages) -> score=2.00 (5 steps)
  [43/50] conv_616ea1de7867546700NNwtXfk... (10 messages) -> score=2.00 (5 steps)
  [44/50] conv_af7593a4a912c87e00sTDdPkG... (8 messages) -> score=2.00 (4 steps)
  [45/50] conv_dd7d597e6caf6ab800AgJVCH2... (8 messages) -> score=2.00 (4 steps)
  [46/50] conv_76235c6440aa642b004iGevg5... (10 messages) -> score=2.00 (5 steps)
  [47/50] conv_273e4fb5ad46a43f00kqN4xLl... (10 messages) -> score=2.00 (5 steps)
  [48/50] conv_d0cc031ff64b6fb900a0N2UT2... (10 messages) -> score=2.00 (5 steps)
  [49/50] conv_3b71a467cea1cad2006CYMLhg... (8 messages) -> score=2.00 (4 steps)
  [50/50] conv_b6ecc92568fbb94b003AGC89P... (12 messages) -> score=2.00 (6 steps)

  Completed 50 evaluations for airline-customer-service-sim

## Results Summary

Aggregate results per agent and display a summary table.

In [18]:
import math

# Build summary DataFrames
for agent_name, results in all_results.items():
    print(f"\n{'='*60}")
    print(f"Agent: {agent_name}")
    print(f"{'='*60}")

    df = pd.DataFrame([
        {
            "conversation_id": r["conversation_id"][:30] + "...",
            "messages": r["num_messages"],
            "user_coherence": r["user_coherence"],
            "tokens": r.get("total_tokens", 0),
        }
        for r in results
    ])

    display(df)

    valid_scores = [r["user_coherence"] for r in results if not math.isnan(r["user_coherence"])]
    if valid_scores:
        print(f"\n  Conversations evaluated: {len(valid_scores)}")
        print(f"  Mean user_coherence: {sum(valid_scores)/len(valid_scores):.3f}")
        print(f"  Min: {min(valid_scores):.2f}, Max: {max(valid_scores):.2f}")
        print(f"  Std: {pd.Series(valid_scores).std():.3f}")
    else:
        print("  No valid scores")

============================================================
Agent: legal-contract-review-sim
============================================================

                      conversation_id  messages  user_coherence  tokens
0   conv_0842a7cbecd7e0cf00uPEBlTj...        10             2.0    5321
1   conv_c43ff32bd5c4f0f800gDkl0Wz...        10             2.0    4753
2   conv_8d4b2d823e8a1d2100HK9q8gZ...        10             2.0    4656
3   conv_a52d0cd1505aa0920098fmBAk...        10             2.0    4430
4   conv_a2650e815ac77d7d00sjZYSMb...        10             2.0    5358
5   conv_5844bba372c6c36f00wFpFAQQ...        11             2.0    5268
6   conv_3b52bf7f44771fe400lXmmUqE...         9             2.0    4592
7   conv_7d4e3ef070b0583c00bekHSCL...         8             2.0    5666
8   conv_7309955b0d21b1d400p14ZoDT...         8             2.0    4749
9   conv_f064f710eb0666b800Iv1UBib...        10             2.0    5111
10  conv_4dd34510dd1753f6003QwF4Ot...        11             2.0    4486
11  conv_df1c9b1bbf35a8cc00vsHQm0s...        10             2.0    4095
12  conv_ce3d8ef424fb59f400LBSnYtH...        12             2.0    4629
13  conv_b0177754bb0366d400N8uT3fD...        10             2.0    4157
14  conv_f137285354cd0abd00Fw1NITi...        12             2.0    4545
15  conv_4346b89a2062620a00yefxPIP...        10             2.0    3639
16  conv_6c7ff3c0fcfcd45300ZHAkgCb...        10             2.0    5189
17  conv_bd1ce398f7b23db70058mU0dO...         8             2.0    5579
18  conv_dae72f5e231910a800Pa8K76r...         8             2.0    4047
19  conv_5c49a5f5d167d50500tpXam6g...         8             2.0    3853
20  conv_091d7a5f3d767a5200PJuXlTT...        10             2.0    4541
21  conv_0f94e0cfd39b257b00uHlJwJS...        13             2.0    5059
22  conv_6ad29d39b891ca5100KhgL3tK...        10             2.0    5053
23  conv_7f53f6b392b7e67600j8MPraI...        10             2.0    5129
24  conv_7b665a69c2b4419900az2VP22...         8             2.0    4809
25  conv_61b3fb35b27b2d0500FHbTrmA...        13             2.0    4417
26  conv_819771956b847c5700LzWrvjm...        11             2.0    4736
27  conv_99bbc2dba2c24db100HRVjYmn...        10             2.0    4822
28  conv_ee4f4fda424d6cc400IjP4tR0...        11             2.0    4156
29  conv_df8193ed23a25c1200zIOjB1w...        10             2.0    5230
30  conv_d83f9b8363196b0e00f7ej968...        12             2.0    5149
31  conv_999652fcbf311f3f00fL3BBFl...        10             2.0    4468
32  conv_7a1d62deaf729bcb00masxGIE...        13             2.0    4619
33  conv_2e9213ad12e0c99300O9nmtsk...        10             2.0    4557
34  conv_3b3517b1d014029600zoN09yp...        10             2.0    4061
35  conv_c89b39972733ce0600S9nCfZQ...        10             2.0    5602
36  conv_1c37d407f98cdec600iNOSllp...        10             2.0    4812
37  conv_703955bd31cc759a00kCSuMd2...        10             2.0    4415
38  conv_a67487def52f364400TBz043t...        12             2.0    6067
39  conv_d7f6d586e422413b00o0oRGRZ...        10             2.0    5730
40  conv_2dd77c2c7a8337b6001bEhVP1...        10             2.0    6063
41  conv_a7c84f31481c17e5002q6Chi5...        11             2.0    5170
42  conv_4f80efde464a376200vhL6InT...         6             2.0    4795
43  conv_a414274f0fe62d2900xXEfXzt...         6             2.0    4634
44  conv_f8e3cc4fd26ff27000dob3B4f...         8             2.0    5789
45  conv_2a8225c918083612004OQvvrm...        10             2.0    6228
46  conv_d2818f234d162edc00jjhyEiC...        10             2.0    5598
47  conv_4ab42f1ea7a4884000CsIriO3...         8             2.0    5202
48  conv_e97a0580bd35af36000AEgc4x...        10             2.0    5426
49  conv_ccb55e868b89dc6a00NdIhjeR...        10             2.0    6002

  Conversations evaluated: 50
  Mean user_coherence: 2.000
  Min: 2.00, Max: 2.00
  Std: 0.000

============================================================
Agent: airline-customer-service-sim
============================================================

                      conversation_id  messages  user_coherence  tokens
0   conv_b4dd30d64e6b0dc300V6yB6BN...        10             2.0    3743
1   conv_06b3877fbbeca15200ZMTAGL9...        15             2.0    4584
2   conv_84f6392575738eba00kqxeUlq...        14             2.0    4780
3   conv_4b0a422287a2e5cb00PtEbvVz...        17             2.0    5334
4   conv_c2385265a03d6fba00eGzsnQB...        14             2.0    4756
5   conv_eb3c9f2328e4671d00RC5hJ04...        15             2.0    4586
6   conv_ce490d3bf1b340e00071ZcwPo...        13             2.0    4443
7   conv_6341b1140363451400dpZZEIX...        10             2.0    3779
8   conv_54d29dbaf3d92b3800UlavsFp...        14             2.0    4452
9   conv_064412c823b1ad0b00gCO1sEj...        17             2.0    4863
10  conv_7ac6d01371e75aa100dwgPblZ...        10             2.0    3621
11  conv_d33fe3b9ffa296050001mzCiV...        10             2.0    3638
12  conv_3139403df8a7a65700YVUKPx1...         8             2.0    3361
13  conv_6a9f27df9fee4dc000iSeHHYT...         8             2.0    3257
14  conv_cca7fae6ade4edf7004mUjm96...         8             2.0    3252
15  conv_26f4905bc3b22f6b00t99AacL...        10             2.0    3534
16  conv_675268409258dad100z8EAWXl...        10             2.0    3765
17  conv_c478f6e0705f5bb300sGo52FE...        10             2.0    3468
18  conv_6dd38d9ab2b2c13700yvtl3od...         8             2.0    3295
19  conv_b925dc46d1f2dad400U6Ezk9Z...        10             2.0    3534
20  conv_087adc3b102d1b4800SQhtupW...        12             2.0    4119
21  conv_2fbca287fc50b7fc00nLcPSnX...        12             2.0    3768
22  conv_f4e7e11b1db00c6a00MI6S78r...        17             2.0    4296
23  conv_90b3666b17095e5900LLAhzZe...        12             2.0    4104
24  conv_01b60d72463e956800r5t8JRW...        12             2.0    3797
25  conv_485e96aa3edd859d0035jHcex...        10             2.0    3915
26  conv_f39d463408b9916a00kK3eeU9...        14             2.0    4917
27  conv_a325abdfa6ef95c300F4kWx74...        14             2.0    4322
28  conv_b802f521b498b1dd00ckUFk7b...        12             2.0    3792
29  conv_98de85b4e7e5d05100wwwuxMx...        16             2.0    4374
30  conv_6f35fe661e5d8a6300If1bwqt...        14             2.0    4394
31  conv_e0e1348e93b022ca008It33YZ...        12             2.0    4217
32  conv_6bdc7f991ed5bfa400XRkLBqx...        14             2.0    4662
33  conv_111c15ff83716cc600COHmNvl...        14             2.0    4554
34  conv_3245e7ab86535f6800enP0Hdz...        16             2.0    4521
35  conv_598dd3d42653ed0300qJ1Izvg...        13             2.0    3867
36  conv_87f559256e3b1d3900wpcik16...        14             2.0    4470
37  conv_e345bd64382740fc00NhegzB5...        15             2.0    4481
38  conv_6f8682b842b85bb900GuqTXEY...        16             2.0    4747
39  conv_b9b0b4297656ef8800hmovdiP...        12             2.0    4067
40  conv_a509881dd413e5e700AHN5A9l...         9             2.0    3359
41  conv_c32dc578676cf11c00YIq7oaH...        10             2.0    3519
42  conv_616ea1de7867546700NNwtXfk...        10             2.0    3531
43  conv_af7593a4a912c87e00sTDdPkG...         8             2.0    3339
44  conv_dd7d597e6caf6ab800AgJVCH2...         8             2.0    3273
45  conv_76235c6440aa642b004iGevg5...        10             2.0    3351
46  conv_273e4fb5ad46a43f00kqN4xLl...        10             2.0    3575
47  conv_d0cc031ff64b6fb900a0N2UT2...        10             2.0    3529
48  conv_3b71a467cea1cad2006CYMLhg...         8             2.0    3311
49  conv_b6ecc92568fbb94b003AGC89P...        12             2.0    3741

  Conversations evaluated: 50
  Mean user_coherence: 2.000
  Min: 2.00, Max: 2.00
  Std: 0.000

## Per-Step Score Distribution

Visualize the distribution of per-step derail scores across all conversations for each agent.

In [16]:
from collections import Counter

for agent_name, results in all_results.items():
    print(f"\n{'='*60}")
    print(f"Agent: {agent_name} — Per-Step Score Distribution")
    print(f"{'='*60}")

    score_counts = Counter()
    total_steps = 0
    derailed_conversations = []

    for r in results:
        per_step = r.get("per_step_scores", [])
        for step in per_step:
            s = step.get("derail_score")
            if s is not None:
                score_counts[s] += 1
                total_steps += 1

        # Flag conversations with any score=0 (derailed)
        zeros = [step for step in per_step if step.get("derail_score") == 0]
        if zeros:
            derailed_conversations.append({
                "conversation_id": r["conversation_id"][:30] + "...",
                "derailed_steps": [
                    {"step": z.get("conversation_step"), "explanation": z.get("explanation", "")}
                    for z in zeros
                ],
            })

    print(f"\n  Total scored steps: {total_steps}")
    for score in [2, 1, 0]:
        count = score_counts.get(score, 0)
        pct = (count / total_steps * 100) if total_steps else 0
        bar = "█" * int(pct / 2)
        label = {2: "Likely/logical", 1: "Weak/possible", 0: "Not logical"}[score]
        print(f"  Score {score} ({label}): {count:3d} ({pct:5.1f}%) {bar}")

    if derailed_conversations:
        print(f"\n  Conversations with derailed steps (score=0):")
        for dc in derailed_conversations:
            print(f"    {dc['conversation_id']}")
            for ds in dc["derailed_steps"]:
                print(f"      Step {ds['step']}: {ds['explanation']}")

============================================================
Agent: legal-contract-review-sim — Per-Step Score Distribution
============================================================

  Total scored steps: 194
  Score 2 (Likely/logical): 194 (100.0%) ██████████████████████████████████████████████████
  Score 1 (Weak/possible):   0 (  0.0%)
  Score 0 (Not logical):   0 (  0.0%)

============================================================
Agent: airline-customer-service-sim — Per-Step Score Distribution
============================================================

  Total scored steps: 244
  Score 2 (Likely/logical): 244 (100.0%) ██████████████████████████████████████████████████
  Score 1 (Weak/possible):   0 (  0.0%)
  Score 0 (Not logical):   0 (  0.0%)

## Save Results

Save the full evaluation results (including per-step details) to JSON files.

In [17]:
for agent_name, results in all_results.items():
    output_file = f"{agent_name}_user_coherence_results.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"Saved {len(results)} results to {output_file}")

Saved 50 results to legal-contract-review-sim_user_coherence_results.json
Saved 50 results to airline-customer-service-sim_user_coherence_results.json